"""create initial expenses table

Revision ID: 30b0a4afe4c8
Revises: 
Create Date: 2026-03-30 13:39:10.961857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b0a4afe4c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'cat',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('items', 'item',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_items_cat_id'), 'items', ['cat_id'], unique=False)
    op.create_index(op.f('ix_items_item'), 'items', ['item'], unique=True)
    op.alter_column('main', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('main', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('main', 'raw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_main_created'), 'main', ['created'], unique=False)
    op.create_index(op.f('ix_main_user_id'), 'main', ['user_id'], unique=False)
    op.drop_constraint(None, 'main', type_='foreignkey')
    op.create_foreign_key(None, 'main', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main', type_='foreignkey')
    op.create_foreign_key(None, 'main', 'items', ['item_id'], ['id'])
    op.drop_index(op.f('ix_main_user_id'), table_name='main')
    op.drop_index(op.f('ix_main_created'), table_name='main')
    op.alter_column('main', 'raw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('main', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('main', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_items_item'), table_name='items')
    op.drop_index(op.f('ix_items_cat_id'), table_name='items')
    op.alter_column('items', 'item',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('categories', 'cat',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
