"""create depo table

Revision ID: bcdb2f34c3ac
Revises: 8b68bbe39691
Create Date: 2026-04-01 15:01:57.786823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcdb2f34c3ac'
down_revision: Union[str, Sequence[str], None] = '8b68bbe39691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('categories', 'cat',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('items', 'item',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_items_cat_id'), 'items', ['cat_id'], unique=False)
    op.create_index(op.f('ix_items_item'), 'items', ['item'], unique=True)
    op.alter_column('main', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('main', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('main', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('main', 'raw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('main', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_main_user_id'), 'main', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_user_id'), table_name='main')
    op.alter_column('main', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('main', 'raw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('main', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('main', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('main', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_items_item'), table_name='items')
    op.drop_index(op.f('ix_items_cat_id'), table_name='items')
    op.alter_column('items', 'item',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('categories', 'cat',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
